name: Suggest Alternative
description: Suggest an alternative app to an Adobe app.
body:
  - type: markdown
    attributes:
      value: |
        Please make sure all information is correct before submitting this form.<br>
        If you don't see any text below, please go [here](https://ass.easun.me/submit) to fill out the form. It'll bring you back here with your information formatted and filled correctly. If you don't go through the form, I will not add your app.<br>
        Thank you for understanding!
  - type: textarea
    id: generated-content
    attributes:
      label: Website-Generated Content
      description: PLEASE DO NOT TOUCH THIS AREA. It only makes it more difficult/time-consuming to add your app. Thank you.
      placeholder: If you see this, go to the link above to generate content required here.
    validations:
      required: true
