name: Suggest Alternative
description: Suggest an alternative app to an Adobe app.
title: "Alternative: "

body:
  - type: textarea
    id: generated-content
    attributes:
      label: Website-Generated Content
      description: PLEASE DO NOT TOUCH THIS AREA. It only makes it more difficult to add your app. Thank you.
      placeholder: If you see this, go to https://ass.easun.me/submit to generate content seen here.
