blank_issues_enabled: true
contact_links:
  - name: Alternative submissions are not being processed currently!
    url: https://github.community/
    about: I&#39;m redesigning the website to be faster/easier to work with on both my end and the visitor&#39;s end. Thanks for being patient!.
