blank_issues_enabled: true
contact_links:
  - name: -- GO HERE TO SUBMIT AN APP! --
    url: https://ass.easun.me/submit
    about: Please go through the website so that adding your app is easier for both sides. Your app will not be added if you do not go through the form.
