blank_issues_enabled: true
contact_links:
  - name: Alternative submissions are not being processed currently!
    url: https://github.com/eaaasun/adobe-sucks-scrotum
    about: I'm redesigning the website to be faster/easier to work with on both my end and the visitor's end. Thanks for being patient!. (Submissions are still welcome)
