backend:
  name: git-gateway
  branch: metalsmith-cms

media_folder: "src/uploads"
public_folder: "../../uploads"
publish_mode: editorial_workflow

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Replaces"
        name: "adobeApps"
        widget: "list"
        allow_add: true
        required: true
        fields:
          - label: "Adobe App Name"
            widget: "select"
            name: "name"
            options: ["Acrobat", "After Effects", "Animate", "Audition", "Dreamweaver", "InDesign", "Illustrator", "Lightroom", "Photoshop", "Premiere", "Substance", "Other"]
          - label: "Adobe App Abbreviation"
            name: "abbreviation"
            widget: "select"
            options: ["ACR", "AE", "AN", "AU", "DW", "ID", "AI", "LR", "PS", "PR", "SU", "OTHER"]

      - label: "Pricing"
        widget: "select"
        name: "price"
        options: ["Free", "Paid", "FOSS"]

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Download Link"
        name: "downloadLink"
        widget: "string"